### ISSUE TITLE
training on custom dataset

### ISSUE THREAD

**Issue by nicholasguimaraes** [dronefreak/human-action-classification#11]
Hello @dronefreak, first of all thank you for the incredible work!

I got a question on how to train the network with my own dataset.

In the retrain.py file am I training 2 networks, one for pose and another for scene classification?

**Comment by dronefreak** [comment]
Hello,

Well, pose estimation is pre-trained, and we do not touch that model since it was trained on multiple GPUs. Essentially, we only re-train or finetune the scene classification algorithm, because this finetuning is achievable on single small-scale GPUs. Please let me know your exact doubts so that I can assist you further.

**Comment by nicholasguimaraes** [comment]
Great! Another doubt, lets say I'm using the pretrained Stanford 40 model and we have 2 or more different actions in the screen simultaneously. Is it possible to print out on top of each person the name of the action instead of printing it on the top left of the screen?

**Comment by dronefreak** [comment]
Sure. The way this architecture was designed is that instead of one-hot encoding the outcomes, we generate class probabilities of the different possible predictions. Only the top five probabilities are selected and out of those, the action with the highest probability is selected and displayed. You can just literally select the top-2 or top-3 probabilities that you think there are in the present image, and modify the visualizations accordingly.

Furthermore, if there are more than one actions present in the image, the probabilities will get adjusted accordingly, like 40% watching television and 40% working on computer etc.
